### ISSUE TITLE
Refactoring of icon handling

### ISSUE THREAD

**Issue by KUTlime** [KUTlime/PowerShell-Open-Here-Module#13]
The current approach of icon handling is to create a folder in `LOCALDATA`, download the shell's icon from the GitHub repository or create the icon when download fails from a base64 string.

The new approach will use EXE icon by default, brings a new switch `-UseCustomIcon` to the `Set-OpenHereShortcut`. The current approach will be used when `-UseCustomIcon` will be present in a `SetOpenHereShortcut` call.

**Comment by JuhJuhButts** [comment]
Thanks for adding this. Could you update the docs?

**Comment by solvingj** [comment]
Amazing, thank you!
