### ISSUE TITLE
Why does a powershell screen flash before launching the terminal

### ISSUE THREAD

**Issue by musm** [KUTlime/PowerShell-Open-Here-Module#14]

**Comment by KUTlime** [comment]
Kindly, [read the documentation first](https://github.com/KUTlime/PowerShell-Open-Here-Module#notes) before you posting a new issue. Thank you.

**Comment by musm** [comment]
Ops pressed enter before I actually submitted the gif 
![a](https://user-images.githubusercontent.com/4319522/78576374-94c9bd80-77fa-11ea-8605-970ba1d94c1e.gif)

**Comment by musm** [comment]
ANyways thanks I see the issue now
