### ISSUE TITLE
Opening specific profile in Windows Terminal

### ISSUE THREAD

**Issue by hanjo** [KUTlime/PowerShell-Open-Here-Module#22]
Hi,
is it possible to use this to open a specific profile (i.e. not the default profile) in Windows Terminal?
For example, my default profile is the WSL Bash, but I would like to open a powershell tab in Windows Terminal.
Thanks

**Comment by KUTlime** [comment]
Hi @hanjo 
thx for an interest of this module. 

# Quick answer
Yes, you can modify the registry key created by `Set-OpenHereShortcut` to run any profile. Look into module's source code to registry key path and follow [this](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows) guidelines for profile option.

# Long answer
There is a catch with your request. Actually, several of them.

1. One of the key fundamental of this module is **consistency**. This feature violates this fundamental by focusing on implementation details related to Windows Terminal. I could come up with a new function to handle this functionality to be consistent but...
2. There is a limit for elevated shortcuts in one subfolder in the Windows context menu. There could be only one elevated command. I could create as many as possible non-elevated shortcut (_profiles_) but only one elevated shortcut. If I give you a function to manipulate with Windows Terminal profiles, there would be an obvious question to ask: _How about to generate all the profiles into the context menu?_ This brings us back to 1) and recursively to 2). 
3. You could have a wide range of profiles with wild customization and this could create more problems than solution when we are talking about auto-generated shortcuts. E.g. you need a icons for all profiles.
4. Windows Terminal is far from feature complete. It has a lot of bugs and my goal is to keep a relation to Windows Terminal at the least possible level right now. This approach changes when Windows Terminal will be more feature completed.

# Summary
There is a [tool](https://github.com/lextm/windowsterminal-shell) ([_and many others_](https://github.com/kerol2r20/Windows-terminal-context-menu)) with similar functionality which you are asking for. I have doubts about a proper functionality of these tools. Many of them neglecting special cases in paths like non-English characters or click on drive.

I will analyze this tool and probably implement some functionality sooner or later but I can't give you and date when it will be completed.

**Comment by hanjo** [comment]
Hi @KUTlime 
thanks for the explanation, this makes perfect sense. I'm looking forward to future releases then :-)

**Comment by KUTlime** [comment]
BTW: I've this issue https://github.com/microsoft/terminal/issues/3158 
I could say that this request will be obsolete if they implement this. 🤷🏿‍♂️
