### ISSUE TITLE
Create an Admin menu item at the top level

### ISSUE THREAD

**Issue by a-i-joe** [KUTlime/PowerShell-Open-Here-Module#24]
The extra click to expand the menu to get to an admin-level context menu item seems to be unavoidable with the current options.

It seems that flexibility would be greatly enhanced by generalizing this solution to be able to specify that you are trying to create a top-level item rather than something in a expanding menu.

**Comment by KUTlime** [comment]
Dear @a-i-joe this discussion already has been made in #20 .
The result is still the same.

Closing as `wonfix`
