### ISSUE TITLE
Please add the option to add a Powershell 7 context menu item.

### ISSUE THREAD

**Issue by WouterVanGoey** [KUTlime/PowerShell-Open-Here-Module#27]

**Comment by KUTlime** [comment]
It is already there

`Set-OpenHereShortcut -ShortcutType:PowerShellCore`

**Comment by WouterVanGoey** [comment]
Hi, I did not realize that that was the new PowerShell, thanks.
I ran the command and have the context menu but only the regular open here opens powershell in the new terminal app.
When I select Open here as Administrator it opens a window in pwsh.exe. Is there a way I can have it run Windows Terminal?

**Comment by KUTlime** [comment]
> Hi, I did not realize that that was the new PowerShell, thanks. I ran the command and have the context menu but only the regular open here opens powershell in the new terminal app. When I select Open here as Administrator it opens a window in pwsh.exe. Is there a way I can have it run Windows Terminal?

Sure, that is easy! 

1. Make the Windows Terminal OpenHere shortcut.
2. Set Windows PowerShell as a default profile.
3. Bam, you have it.

or

1. Make Windows Terminal as default console host (_in Windows settings_).
2. Make the Windows PowerShell OpenHere shortcut.
3. Any request will be pickup by Windows Terminal and it should be in the desired location.
