### ISSUE TITLE
open all in a single window

### ISSUE THREAD

**Issue by lisonge** [KUTlime/PowerShell-Open-Here-Module#4]
![image](https://user-images.githubusercontent.com/38517192/75173579-0e857a80-576a-11ea-9063-37429772100e.png)
when i click "Open here" and I had a window open earlier, i hope they all open in a window.
in other words, when i click "Open here" twice, they are both in  a window
***
![image](https://user-images.githubusercontent.com/38517192/75173474-e5fd8080-5769-11ea-9a8c-100eedb75ed9.png)
↑ this is NOT what i want
***
![image](https://user-images.githubusercontent.com/38517192/75173939-a08d8300-576a-11ea-9688-e3b927139580.png)
↑ this is what i want

**Comment by KUTlime** [comment]
@lisonge Are you sure that this could be achieved through [the command line argument](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md) of Windows Terminal? Could you provide me a sample how to achieve this? 

And what if someone wants the opposite what _you_ want?
And what if someone wants not new tab but split-pane instead?
And what if someone wants the new panel with particular shell next to existing panels?
...and so on and so forth.

I can open some sort of customization but this is a very tricky path. Especially with Windows Terminal.

**Comment by KUTlime** [comment]
Closing for timeout.

**Comment by sebader** [comment]
I would vote for this feature (if this is technically possible) as well. One of the beauties of Windows Terminal is the Tabs feature. Opening a new window every time defeats the main purpose of it - at least for me.

**Comment by KUTlime** [comment]
Yeah, but the questions raised by me in my first response still stands. 😉
